config:
  # This is a test server run by team Artillery
  # It's designed to be highly scalable
  target: https://psc.britam.com
  phases:
    - duration: 60
      arrivalRate: 1
      rampTo: 5
      name: Warm up phase
    - duration: 60
      arrivalRate: 5
      rampTo: 10
      name: Ramp up load
    - duration: 30
      arrivalRate: 10
      rampTo: 30
      name: Spike phase
  # Load & configure a couple of useful plugins
  # https://docs.art/reference/extensions
  plugins:
    ensure: {}
    apdex: {}
    metrics-by-endpoint: {}
  engines:
    playwright: {}
    http: {}
  apdex:
    threshold: 100
  ensure:
      thresholds:
        - http.response_time.p99: 100
        - http.response_time.p95: 75
scenarios:

  - flow:
      - loop:
        - get:
            url: "https://psc.britam.com"
            include: "./tests/login-PSC.spec.js"
        count: 100
